// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SmartCmdArgs
{
    internal sealed partial class Vsix
    {
        public const string Id = "SmartCmdArgs15.0248c5c8-b4c5-4201-9360-5c100580f52e";
        public const string Name = "Smart Command Line Arguments VS2017";
        public const string Description = @"A Visual Studio 2017 Extension which aims to provide a better UI to manage your command line arguments.";
        public const string Language = "en-US";
        public const string Version = "2.6.0.3";
        public const string Author = "Irame & MBulli";
        public const string Tags = "Commandline Command Line Arguments cmd project";
    }
}
