// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SmartCmdArgs
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCmdArgsToolWindowPackageString = "131b0c0a-5dd0-4680-b261-86ab5387b86e";
        public static Guid guidCmdArgsToolWindowPackage = new Guid(guidCmdArgsToolWindowPackageString);

        public const string guidToolWindowString = "a21b35ed-5c13-4d55-a3d2-71054c4e9540";
        public static Guid guidToolWindow = new Guid(guidToolWindowString);

        public const string guidVSMenuCmdSetString = "c5334667-5dda-4f4a-bc24-6e0084dc5068";
        public static Guid guidVSMenuCmdSet = new Guid(guidVSMenuCmdSetString);

        public const string guidCmdArgsToolBarCmdSetString = "53d59879-7413-491e-988c-938117b773e3";
        public static Guid guidCmdArgsToolBarCmdSet = new Guid(guidCmdArgsToolBarCmdSetString);

        public const string guidCustomMonikersString = "cafdbdaf-1847-4824-8957-a169d25d0cfb";
        public static Guid guidCustomMonikers = new Guid(guidCustomMonikersString);

        public const string guidImagesString = "b7f63abd-939f-4912-912e-e98c7cc9ef6f";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindowCommandId = 0x0100;
        public const int ToolbarAddCommandId = 0x1100;
        public const int ToolbarRemoveCommandId = 0x1101;
        public const int ToolbarMoveUpCommandId = 0x1102;
        public const int ToolbarMoveDownCommandId = 0x1103;
        public const int ToolbarCopyCommandlineCommandId = 0x1104;
        public const int ToolbarAddGroupCommandId = 0x1105;
        public const int ToolbarShowAllProjectsCommandId = 0x1106;
        public const int ToolbarOpenSettingsCommandId = 0x1107;
        public const int ToolbarAddEnvVarId = 0x1108;
        public const int ToolbarCopyEnvVarsForPSCommandId = 0x1109;
        public const int ToolbarCopyEnvVarsForCMDCommandId = 0x110A;
        public const int ToolbarAddWorkDirId = 0x110B;
        public const int ToolbarAddLaunchAppId = 0x110C;
        public const int TWToolbar = 0x1000;
        public const int TWToolbarGroupAddRemove = 0x1050;
        public const int TWToolbarGroupMove = 0x1051;
        public const int TWToolbarEdit = 0x1052;
        public const int TWToolbarSettings = 0x1053;
        public const int TWToolbarGroupAdd = 0x1054;
        public const int TWToolbarGroupCopyCommandLine = 0x1055;
        public const int TWToolbarGroupCopyEnvVars = 0x1056;
        public const int ToolbarAddMenuController = 0x1201;
        public const int ToolbarCopyCommandLineMenuController = 0x1202;
        public const int ToolbarCopyEnvVarsMenu = 0x1203;
        public const int CopyCmdLineIcon = 0x0001;
        public const int bmpVSMenuIcon = 0x0001;
    }
}