// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SmartCmdArgs
{
    internal sealed partial class Vsix
    {
        public const string Id = "SmartCmdArgs.Markus B.9fb78f2a-71cb-4437-b32f-d875e376bacf";
        public const string Name = "Smart Command Line Arguments VS2019";
        public const string Description = @"A Visual Studio 2019 Extension which aims to provide a better UI to manage your command line arguments.";
        public const string Language = "en-US";
        public const string Version = "3.0.3.1";
        public const string Author = "Irame & MBulli";
        public const string Tags = "Commandline Command Line Arguments cmd project";
    }
}
