// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SmartCmdArgs
{
    internal sealed partial class Vsix
    {
        public const string Id = "SmartCmdArgs17.6edd462d-d4d6-40b9-a7b4-451a6ce6c527";
        public const string Name = "Smart Command Line Arguments VS2022";
        public const string Description = @"A Visual Studio 2022 Extension which aims to provide a better UI to manage your command line arguments.";
        public const string Language = "en-US";
        public const string Version = "3.3.0";
        public const string Author = "Irame & MBulli";
        public const string Tags = "Commandline Command Line Arguments cmd project";
        public const bool IsPreview = false;
    }
}
